### ISSUE TITLE
v2.6.1混淆打包后setDWLivePlayParams崩溃异常

### ISSUE THREAD

**Issue by mayemonkey** [CCVideo/Live_Android_Play_SDK#1]
`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.bokecc.sdk.mobile.live.pojo.TemplateInfo.getPdfView()' on a null object reference
                                                             at com.bokecc.sdk.mobile.live.DWLive.setDWLivePlayParams(DWLive.java:249)
                                                             at com.xxx.ui.activity.PcLivePlayActivity.initPlayer(PcLivePlayActivity.java:1028)
                                                             at com.xxx.ui.activity.PcLivePlayActivity.onViewCreated(PcLivePlayActivity.java:482)
                                                             at com.xxx.ui.activity.base.RyxBaseActivity.onCreate(RyxBaseActivity.java:46)
                                                             at com.xxx.ui.activity.PcLivePlayActivity.onCreate(PcLivePlayActivity.java:304)
                                                             at android.app.Activity.performCreate(Activity.java:7057)
                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2808)
                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2930) 
                                                             at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1619) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                             at android.os.Looper.loop(Looper.java:171) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:6684) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783) `

- 避免混淆配置已添加
- 执行DWLive.getInstance().setDWLivePlayParams(myDWLiveListener, this, docView, player);时发生异常
- 取消混淆后异常不会发生

**Comment by renhui** [comment]
@mayemonkey 
可以尝试
```
-keep public class com.bokecc.sdk.mobile.**{*;}
-keep public class tv.**{*;}
-keep public interface com.bokecc.sdk.mobile.**{*;}
-keep class org.webrtc.**{*;}
```

**Comment by mayemonkey** [comment]
以上混淆规则打包时已经添加，依然出现该问题
